import { CategoryData, ProductData, BannerData, PromotionData, StoreConfigData } from '@/types';

export const mockConfig: StoreConfigData = {
  id: 'default',
  name: 'Henri Imports',
  logoUrl: '/logo.png',
  bannerUrl: '/images/hero-banner.png',
  primaryColor: '#7c3aed',
  secondaryColor: '#f3f4f6',
  textColor: '#0f172a',
  whatsapp: '5511999999999',
  instagram: '@henri.imports',
  facebook: 'henriimportsoficial',
  address: 'Av. Paulista, 1000 - Bela Vista, São Paulo - SP',
  latitude: -23.5616,
  longitude: -46.656,
  cep: '01310-100',
  businessHours: 'Segunda a Sábado: 10h às 22h | Domingo: 12h às 18h',
  deliveryMode: 'FAIXAS',
  deliveryKmRate: 2.5,
  deliveryRanges: [
    { maxKm: 3, price: 10.0 },
    { maxKm: 5, price: 15.0 },
    { maxKm: 8, price: 20.0 },
    { maxKm: 15, price: 30.0 },
  ],
  pixKey: '11999999999',
  pixName: 'Henri Imports Vape & Tabacaria',
  whatsappTemplate: 'Novo Pedido Henri Imports',
};

export const mockCategories: CategoryData[] = [
  {
    id: 'cat-1',
    name: 'Pods Descartáveis',
    slug: 'pods-descartaveis',
    icon: 'Zap',
    imageUrl: '/images/ignite-main.png',
    color: '#7c3aed',
    displayOrder: 1,
    active: true,
    productCount: 14,
  },
  {
    id: 'cat-2',
    name: 'Vapes & Juices',
    slug: 'vapes-juices',
    icon: 'Wind',
    imageUrl: '/images/elfbar-main.png',
    color: '#a855f7',
    displayOrder: 2,
    active: true,
    productCount: 8,
  },
  {
    id: 'cat-3',
    name: 'Essências',
    slug: 'essencias',
    icon: 'Flame',
    imageUrl: '/images/essencia-zomo.png',
    color: '#ec4899',
    displayOrder: 3,
    active: true,
    productCount: 22,
  },
  {
    id: 'cat-4',
    name: 'Narguilés',
    slug: 'narguiles',
    icon: 'Sparkles',
    imageUrl: '/images/triton-hookah.png',
    color: '#6366f1',
    displayOrder: 4,
    active: true,
    productCount: 6,
  },
  {
    id: 'cat-5',
    name: 'Carvões',
    slug: 'carvoes',
    icon: 'Box',
    imageUrl: '/images/carvao-zomo.png',
    color: '#f59e0b',
    displayOrder: 5,
    active: true,
    productCount: 9,
  },
  {
    id: 'cat-6',
    name: 'Sedas & Sedas Flavored',
    slug: 'sedas',
    icon: 'FileText',
    imageUrl: '/images/seda-smoking.png',
    color: '#10b981',
    displayOrder: 6,
    active: true,
    productCount: 18,
  },
  {
    id: 'cat-7',
    name: 'Acessórios Premium',
    slug: 'acessorios',
    icon: 'ShieldAlert',
    imageUrl: '/images/pegador-hookah.png',
    color: '#3b82f6',
    displayOrder: 7,
    active: true,
    productCount: 11,
  },
];

export const mockProducts: ProductData[] = [
  {
    id: 'prod-1',
    name: 'Ignite V250 Pod Descartável 25000 Puffs',
    slug: 'ignite-v250-pod-descartavel',
    brand: 'Ignite',
    categoryId: 'cat-1',
    category: mockCategories[0],
    description: 'O Ignite V250 traz a mais recente tecnologia em vapes descartáveis com incrível capacidade para até 25.000 puxadas, tela digital LED com medidor de e-líquido e bateria recarregável Type-C. Sabor intenso e vapor denso até a última gota.',
    basePrice: 169.9,
    basePromoPrice: 149.9,
    hasFlavors: true,
    baseStock: 45,
    baseSku: 'IGN-V250-BASE',
    internalCode: 'IGN25K',
    mainImageUrl: '/images/ignite-main.png',
    gallery: [
      '/images/ignite-main.png',
      '/images/blueberry-ice.png',
      '/images/grape-ice.png',
      '/images/strawberry-kiwi.png',
      '/images/mint-ice.png',
    ],
    weight: 0.12,
    active: true,
    flavors: [
      {
        id: 'flv-101',
        productId: 'prod-1',
        name: 'Blueberry Ice',
        imageUrl: '/images/blueberry-ice.png',
        price: 149.9,
        stock: 15,
        sku: 'IGN-V250-BLUEICE',
        description: 'Mirtilos frescos colhidos no ápice com um toque gelado refrescante.',
        displayOrder: 1,
        active: true,
      },
      {
        id: 'flv-102',
        productId: 'prod-1',
        name: 'Grape Ice',
        imageUrl: '/images/grape-ice.png',
        price: 149.9,
        stock: 12,
        sku: 'IGN-V250-GRAPEICE',
        description: 'Uva roxa suculenta com mentol glacial premium.',
        displayOrder: 2,
        active: true,
      },
      {
        id: 'flv-103',
        productId: 'prod-1',
        name: 'Strawberry Kiwi',
        imageUrl: '/images/strawberry-kiwi.png',
        price: 154.9,
        stock: 8,
        sku: 'IGN-V250-STRAWKIWI',
        description: 'Associação perfeita entre morango doce e kiwi levemente cítrico.',
        displayOrder: 3,
        active: true,
      },
      {
        id: 'flv-104',
        productId: 'prod-1',
        name: 'Mint Ice',
        imageUrl: '/images/mint-ice.png',
        price: 149.9,
        stock: 10,
        sku: 'IGN-V250-MINTICE',
        description: 'Hortelã mentolada de altíssima intensidade para um frescor inigualável.',
        displayOrder: 4,
        active: true,
      },
    ],
  },
  {
    id: 'prod-2',
    name: 'Elf Bar BC10000 Puffs Descartável',
    slug: 'elf-bar-bc10000-puffs',
    brand: 'Elf Bar',
    categoryId: 'cat-1',
    category: mockCategories[0],
    description: 'Com design ergonômico e revestimento em textura suave, o Elf Bar BC10000 é sinônimo de elegância. Possui tecnologia Quaq Mesh Coil para sabor consistente e bocal anatômico.',
    basePrice: 139.9,
    basePromoPrice: 119.9,
    hasFlavors: true,
    baseStock: 30,
    baseSku: 'ELF-BC10K-BASE',
    internalCode: 'ELF10K',
    mainImageUrl: '/images/elfbar-main.png',
    gallery: [
      '/images/elfbar-main.png',
    ],
    weight: 0.1,
    active: true,
    flavors: [
      {
        id: 'flv-201',
        productId: 'prod-2',
        name: 'Watermelon Ice',
        imageUrl: '/images/elfbar-main.png',
        price: 119.9,
        stock: 10,
        sku: 'ELF-BC10K-WMICE',
        description: 'Melancia gelada e suculenta.',
        displayOrder: 1,
        active: true,
      },
      {
        id: 'flv-202',
        productId: 'prod-2',
        name: 'Strawberry Kiwi',
        imageUrl: '/images/strawberry-kiwi.png',
        price: 119.9,
        stock: 8,
        sku: 'ELF-BC10K-PMW',
        description: 'Mix de morango com kiwi cítrico.',
        displayOrder: 2,
        active: true,
      },
    ],
  },
  {
    id: 'prod-3',
    name: 'Narguilé Completo Triton Zip Setup Black Edition',
    slug: 'narguile-triton-zip-black',
    brand: 'Triton',
    categoryId: 'cat-4',
    category: mockCategories[3],
    description: 'Narguilé compacto de alto desempenho produzido em alumínio anodizado inoxidável. Acompanha vaso de vidro reforçado, prato em alumínio fundido, rosh de cerâmica e mangueira de silicone lavável.',
    basePrice: 349.9,
    basePromoPrice: 299.9,
    hasFlavors: false,
    baseStock: 8,
    baseSku: 'TRITON-ZIP-BLK',
    internalCode: 'NAR001',
    mainImageUrl: '/images/triton-hookah.png',
    gallery: ['/images/triton-hookah.png'],
    weight: 1.8,
    active: true,
  },
  {
    id: 'prod-4',
    name: 'Essência Zomo Strong Mint 50g',
    slug: 'essencia-zomo-strong-mint-50g',
    brand: 'Zomo',
    categoryId: 'cat-3',
    category: mockCategories[2],
    description: 'A mundialmente famosa essência Zomo Strong Mint proporciona uma refrescância intensa incomparável. Produzida com folhas selecionadas e aroma natural de menta.',
    basePrice: 14.9,
    basePromoPrice: 12.9,
    hasFlavors: false,
    baseStock: 120,
    baseSku: 'ZOMO-SM-50G',
    internalCode: 'ESS01',
    mainImageUrl: '/images/essencia-zomo.png',
    gallery: ['/images/essencia-zomo.png'],
    weight: 0.05,
    active: true,
  },
  {
    id: 'prod-5',
    name: 'Carvão de Coco Zomo Hexagonal 1kg',
    slug: 'carvao-de-coco-zomo-1kg',
    brand: 'Zomo',
    categoryId: 'cat-5',
    category: mockCategories[4],
    description: 'Carvão 100% natural feito de fibra de coco sem aditivos químicos. Formato hexagonal que garante acendimento uniforme, sem cheiro e com baixíssimo teor de cinzas.',
    basePrice: 39.9,
    basePromoPrice: 34.9,
    hasFlavors: false,
    baseStock: 50,
    baseSku: 'CARV-ZOMO-1KG',
    internalCode: 'CARV01',
    mainImageUrl: '/images/carvao-zomo.png',
    gallery: ['/images/carvao-zomo.png'],
    weight: 1.0,
    active: true,
  },
  {
    id: 'prod-6',
    name: 'Seda Smoking Deluxe King Size com Piteira',
    slug: 'seda-smoking-deluxe-king-size',
    brand: 'Smoking',
    categoryId: 'cat-6',
    category: mockCategories[5],
    description: 'Papel de queima ultra fina, produzido na Espanha com goma vegetal 100% natural. Edição Deluxe com piteiras de papel de alta gramatura inclusas.',
    basePrice: 11.9,
    basePromoPrice: 9.9,
    hasFlavors: false,
    baseStock: 200,
    baseSku: 'SEDA-SMOK-DELUXE',
    internalCode: 'SEDA01',
    mainImageUrl: '/images/seda-smoking.png',
    gallery: ['/images/seda-smoking.png'],
    weight: 0.02,
    active: true,
  },
  {
    id: 'prod-7',
    name: 'Pegador e Furador de Alumínio Hookah Pro',
    slug: 'pegador-furador-hookah-pro',
    brand: 'Hookah Pro',
    categoryId: 'cat-7',
    category: mockCategories[6],
    description: 'Acessório duplo essencial para amantes de narguilé. Pegador ergonômico reforçado e agulha furadora integrada para esticar o alumínio perfeito.',
    basePrice: 29.9,
    basePromoPrice: 24.9,
    hasFlavors: false,
    baseStock: 35,
    baseSku: 'ACC-PEG-HOOKAH',
    internalCode: 'ACC01',
    mainImageUrl: '/images/pegador-hookah.png',
    gallery: ['/images/pegador-hookah.png'],
    weight: 0.15,
    active: true,
  },
];

export const mockBanners: BannerData[] = [
  {
    id: 'banner-1',
    title: 'Henri Imports - Vape & Tabacaria Premium',
    description: 'As melhores marcas de Pods Descartáveis, Juices, Narguilés e Acessórios com entrega expressa no mesmo dia.',
    imageUrl: '/images/hero-banner.png',
    link: '/search?category=pods-descartaveis',
    active: true,
    displayOrder: 1,
  },
  {
    id: 'banner-2',
    title: 'Lançamento Ignite V250 - 25.000 Puffs',
    description: 'Garanta o seu com desconto exclusivo de lançamento e frete rápido via WhatsApp.',
    imageUrl: '/images/ignite-main.png',
    link: '/product/ignite-v250-pod-descartavel',
    active: true,
    displayOrder: 2,
  },
];

export const mockPromotions: PromotionData[] = [
  {
    id: 'promo-1',
    title: 'Semana do Pod - Até 20% OFF',
    description: 'Na compra de 2 ou mais Pods Descartáveis ganhe desconto automático + Frete Grátis acima de R$ 250.',
    imageUrl: '/images/ignite-main.png',
    buttonText: 'Ver Promoções',
    buttonLink: '/search?promo=true',
    active: true,
  },
];
